Devapm
fanjeffrey/Microsoft pull request #60
Opened 2017-07-17 09:03 UTC by Song2017

add phpMyAdmin_*

2017-07-17 23:19 UTC, fanjeffrey requested changes

2017-07-17 23:19 UTC, fanjeffrey commented on docker-library/apache-php-mysql/README.md
> +  2. Add App Setting Key: DATABASE_TYPE. See [entrypoint.sh](0.2/entrypoint.sh),[azuredeploy.json](azuredeploy.json) here.
add more description for this to make users understand this app setting item.

2017-07-17 23:19 UTC, fanjeffrey commented on docker-library/apache-php-mysql/azuredeploy.json
> +                "appSettings": [
is this "appSettings" parallel now to "siteConfig" ?

2017-07-17 23:19 UTC, fanjeffrey commented on docker-library/apache-php-mysql/README.md
> +- set DATABASE_TYPE with **local** will run built-in MariaDB and phpMyAdmin;
merge this into "manage the built-in MariaDB with the built-in phpMyAdmin"

2017-07-17 23:19 UTC, fanjeffrey commented on docker-library/apache-php-mysql/README.md
>  - manage the build-in MariaDB with the built-in phpMyAdmin;
merge the second in to this line to make it looking like below:

manage the build-in MariaDB with the built-in phpMyAdmin (You need set DATABASE_TYPE to "LOCAL")

2017-07-17 23:19 UTC, fanjeffrey commented on docker-library/apache-php-mysql/0.2/entrypoint.sh
> +	echo "INFO: Local Mariadb and phpMyAdmin Loading ..."
"INFO: loading local MariaDB and phpMyAdmin ..."

2017-07-18 00:49 UTC, Song2017 commented on docker-library/apache-php-mysql/README.md
> +- set DATABASE_TYPE with **local** will run built-in MariaDB and phpMyAdmin;
yeah

2017-07-18 07:39 UTC, fanjeffrey approved these changes

2017-07-18 07:43 UTC, merged